language: node_js
node_js:
  - "18"

install:
  - npm install

script:
  - ng build --prod --base-href /AI-Blog/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/AI-Blog
  on:
    branch: master
