name: Build and Push to gh-pages

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ng build --base-href "https://labmember7.github.io/AI-Blog/"

      - name: Show
        run: ls
